## eric-enmsg-visinaming-nb image version

global:
  registry:
    url: armdocker.rnd.ericsson.se
    pullSecret:
  ingress:
    enmHost:
  timezone:
productInfo:
  # R-State of the product. R State should match helm chart version (3.1.0 -> R2A)
  # To automate it when packaging the helm chart rstate can be generated
  # and below value replaced with correct R-State
  number: CXC 174 2131
  rstate: R1YU
# Number of replicas(pods) to deploy
replicas-eric-enmsg-visinaming-nb: 1
images:
  eric-enmsg-visinaming-nb:
    name: eric-enmsg-visinaming-nb
    tag: 1.0.395-1
  waitInitContainer:
    enabled: true
    name: eric-enm-init-container
    tag: 1.0.402-1
    command: "[ '/bin/sh', '-c', 'bash /var/tmp/check_service.sh -s gossiprouter-cache,gossiprouter-remoting,jms01,postgres,sps'
      ]"
  eric-enm-monitoring:
    enabled: false
    name: eric-enm-monitoring-eap6
    tag: 1.0.448-1
imageCredentials:
  repoPath: proj-enm
  pullPolicy: Always
  registry:
    url:
    pullSecret:
## Configure the service
service:
  name: visinamingnb
  annotations: {}
  labels: {}
## Configure resource requests and limits
resources:
  requests:
    enabled: true
    memory: 4096Mi
  limits:
    enabled: true
    memory: 4096Mi
  monitoring:
    enabled: false
    requests:
      memory:
      cpu:
    limits:
      memory:
      cpu:
# LivenessProbe Health Check configuration.
livenessProbe:
  enabled: true
  command: /opt/ericsson/vmmonitord/bin/ocf_monitor.py
  arguments: --exec_agents
  initialDelaySeconds: 600
  timeoutSeconds: 15
  periodSeconds: 30
  failureThreshold: 1
readinessProbe:
  enabled: true
  command: /opt/ericsson/vmmonitord/bin/ocf_monitor.py
  arguments: --exec_agents
  initialDelaySeconds: 120
  periodSeconds: 30
  timeoutSeconds: 15
  failureThreshold: 1
# Extra Annotations to be added to pod
podAnnotations: {}
## Tolerations for pod assignment
tolerations: []
## Affinity for pod assignment
affinity: {}
# Constrain which nodes your pod is eligible to be scheduled on
nodeAffinity: {}
priorityClassName: ""
## Node selector
nodeSelector: {}
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 0
## Pod Disruption Budget is an indicator of the number of disruptions that can be tolerated at a given time.
podDisruptionBudget:
  maxUnavailable: 1
